Traceback (most recent call last):
  File "c:\Python38\Scripts\python38_practice\Chapter10\errorExample.py", line 4, in <module>
    raise Exception("This is the error message.")
Exception: This is the error message.
